FROM node:16-alpine
LABEL maintainer "Lee Doughty"
RUN apk add --no-cache --upgrade \
          bash git curl nano jq less rsync zip unzip groff \
          python3 python3-dev py3-pip \
          docker \
          aws-cli \
          # Required for pip install of aws-sam-cli and docker-compose:
          gcc musl-dev libffi-dev \ 
     && rm -rf /var/cache/apk/* \
     && pip install --upgrade pip \
     && pip install aws-sam-cli docker-compose 

WORKDIR /root

ENTRYPOINT /bin/bash
